# /dags/profiles/profiles.yml
config:
  partial_parse: true # Recommended for performance
  use_colors: true

medicare_pipeline: # Profile name
  target: prod # Default target
  outputs:
    prod:
      type: bigquery
      method: service-account # Use the Composer worker's SA implicitly
      project: "{{ env_var('GCP_PROJECT_ID') }}" # Use environment variable set below
      dataset: "{{ env_var('BQ_ANALYTICS_DATASET') }}" # Target dataset for dbt models
      threads: 4 # Adjust based on Composer worker size
      location: "{{ env_var('GCP_REGION') }}" # GCP region
      # If not using Composer's SA directly, you might use:
      # method: service-account-json
      # keyfile: /path/to/your/dbt-runner-sa-key.json # Needs secure handling!