[project]
name = "05-batch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.3.5",
    "pandas>=2.2.3",
    "py4j==0.10.9.5",
    "pyspark==3.3.2",
]